
services:
  backend-aiapp:
    container_name: backend-aiapp
    image: backend-aiapp
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./models/myclassifier/1/log_classifier.onnx:/mnt/models/logclassifier/1/model.onnx
    networks: 
      aiapp:
        ipv4_address: 172.20.0.2

  backend-wsserver:
    container_name: backend-wsserver
    image: backend-wsserver
    env_file:
      - .env
    ports:
      - "8765:8765"
    networks: 
      aiapp:
        ipv4_address: 172.20.0.3

  proxy:
    container_name: ailab-proxy-server
    image: ailab-proxy-server
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "8081:8081"
    networks: 
      aiapp:
        ipv4_address: 172.20.0.4

  frontend-aiapp:
    container_name: frontend-aiapp
    image: frontend-aiapp
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks: 
      aiapp:
        ipv4_address: 172.20.0.5

  ollama-granite:
    container_name: ollama-server
    image: ollama-server
    ports:
      - "11434:11434"
    networks: 
      aiapp:
        ipv4_address: 172.20.0.6

  

networks:
  aiapp:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16