kind: Deployment
apiVersion: apps/v1
metadata:
  name: legacycrm-deployment
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legacycrm
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: legacycrm
    spec:
      containers:
        - name: legacycrm
          image: busybox
          command:
            - /bin/sh
            - '-c'
          args:
            - |
              while true; do
                case $((RANDOM % 6)) in
                  0) echo "Lead conversion failed for prospect ID $((RANDOM % 9000 + 1000)) due to missing contact information." ;;
                  1) echo "API endpoint 'getCustomerDetails' is deprecated and will be removed in version 3.2. Use 'fetchCustomerInfo' instead." ;;
                  2) echo "Customer follow-up process for lead ID $((RANDOM % 9000 + 1000)) failed due to missing next action." ;;
                  3) echo "Escalation rule execution failed for ticket ID $((RANDOM % 9000 + 1000)) - undefined escalation level." ;;
                  4) echo "The 'ExportToCSV' feature is outdated. Please migrate to 'ExportToXLSX' by the end of Q3." ;;
                  5) echo "Support for legacy authentication methods will be discontinued after 2025-06-01." ;;
                esac
                sleep 10
              done
