---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-storage
  namespace: ollama
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3-csi

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scc-admin
  namespace: ollama
imagePullSecrets:
- name: myquaycred
# oc adm policy add-scc-to-user privileged -z scc-admin -n ollama 

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: system:openshift:scc:privileged
  namespace: ollama
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: scc-admin
  namespace: ollama

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-granite
  namespace: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-granite
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ollama-granite
    spec:
      # RUN AS PRIVILLEGED USER; BECAUSE ollama create models was done as root. and in order to find those model
      # the image needs to run in privilleged mode.
      # TODO: Need to create the docker image in a different way so that ollama create is run as user.
      securityContext:
        runAsUser: 0
        runAsNonRoot: false
      serviceAccountName: scc-admin
      containers:
      - image: quay.io/rh-ee-anahid/ollama-granite:v6
        imagePullPolicy: Always
        name: ollama-granite
        ports:
        - containerPort: 11434
          protocol: TCP
        resources:
          limits:
            nvidia.com/gpu: "1"
          requests:
            nvidia.com/gpu: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /.ollama
          name: ollama-storage
      restartPolicy: Always
      volumes:
      - name: ollama-storage
        persistentVolumeClaim:
          claimName: ollama-storage


# oc create secret docker-registry quay-pull-secret \
#   --docker-server=quay.io \
#   --docker-username=rh-ee-anahid+sarobot \
#   --docker-password='65URYS5P9209BMQHFDFJBAS04KXTBKH4DN46AMVAEEZE40MK54BHAJP64M3VD4LN' \
#   -n ollama

---
apiVersion: v1
kind: Service
metadata:
  name: ollama-granite-svc
  namespace: ollama
spec:
  ports:
  - port: 11434
    protocol: TCP
    targetPort: 11434
  selector:
    app: ollama-granite
  type: ClusterIP

