apiVersion: v1
kind: Service
metadata:
  name: ollama-granite-svc
  namespace: ollama
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 11434
  selector:
    app: ollama-granite
  type: ClusterIP